### ISSUE TITLE
Ошибка при  установки в Ubuntu 20.04

### ISSUE THREAD

**Issue by SergeyMi37** [natkaida/blogit#3]
(venv) student@st:~/App/blogit$ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
(venv) student@st:~/App/blogit$ python3 manage.py createsuperuser
Имя пользователя (leave blank to use 'student'): admin
Адрес электронной почты: admin@mail.ru
Password: 
Password (again): 
Traceback (most recent call last):
  File "/home/student/App/blogit/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/student/App/blogit/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: users_profile

The above exception was the direct cause of the following exception:
...
странно, нет таблицы users_profile ?

**Comment by natkaida** [comment]
Выполните:
```
python3 manage.py migrate auth
python3 manage.py migrate --run-syncdb
```

**Comment by SergeyMi37** [comment]
Спасиб
